Repository huangsam/ultimate-python, pull requests merged in 2020-10, with the labels that each got.

#12 Integer infos
  ultimatepython/syntax/variable.py
Labels: enhancement

#14 Revisit CircleCI config
  .circleci/config.yml
Labels: enhancement

#15 Add threads lesson
  README.md
  ultimatepython/advanced/threads.py
Labels: enhancement

#16 Reorder advanced section of ToC
  README.md
Labels: documentation

#17 Refactor threads lesson to explore parallelism
  README.md
  ultimatepython/advanced/threads.py
Labels: enhancement

#18 Add mixin lesson
  README.md
  ultimatepython/advanced/mixins.py
Labels: enhancement

#19 Improve mixins lesson
  ultimatepython/advanced/mixins.py
Labels: enhancement

#23 Add Korean README content
  README.ko.md
Labels: documentation, enhancement

#24 Link Python modules in Korean README
  README.ko.md
Labels: documentation

#26 Add README links to README files
  README.ko.md
  README.md
Labels: documentation

#27 Implement deque lesson
  README.ko.md
  README.md
  ultimatepython/data_structures/deque.py
Labels: enhancement

#28 Add module docs for advanced modules
  ultimatepython/advanced/async.py
  ultimatepython/advanced/benchmark.py
  ultimatepython/advanced/context_manager.py
  ultimatepython/advanced/data_format.py
  ultimatepython/advanced/decorator.py
  ultimatepython/advanced/meta_class.py
  ultimatepython/advanced/mixin.py
  ultimatepython/advanced/mocking.py
  ultimatepython/advanced/mro.py
  ultimatepython/advanced/regex.py
  ultimatepython/advanced/thread.py
  ultimatepython/advanced/weak_ref.py
Labels: documentation, enhancement

#29 Add module docs for classes modules
  ultimatepython/classes/abstract_class.py
  ultimatepython/classes/basic_class.py
  ultimatepython/classes/exception_class.py
  ultimatepython/classes/iterator_class.py
Labels: documentation

#30 Add module docs for DS modules
  ultimatepython/data_structures/comprehension.py
  ultimatepython/data_structures/deque.py
  ultimatepython/data_structures/dict.py
  ultimatepython/data_structures/list.py
  ultimatepython/data_structures/set.py
  ultimatepython/data_structures/string.py
  ultimatepython/data_structures/tuple.py
Labels: documentation

#31 Add module docs for syntax modules
  ultimatepython/syntax/conditional.py
  ultimatepython/syntax/expression.py
  ultimatepython/syntax/function.py
  ultimatepython/syntax/loop.py
  ultimatepython/syntax/variable.py
Labels: documentation

#32 Enhance module docs of classes modules
  ultimatepython/classes/abstract_class.py
  ultimatepython/classes/basic_class.py
  ultimatepython/classes/exception_class.py
  ultimatepython/classes/iterator_class.py
Labels: documentation
